### ISSUE TITLE
Buff Icons not appearing for xivparty

### ISSUE THREAD

**Issue by wolfthefallen** [XIBrixy/Custom-Addons#1]
First, It is fantastic that you released this!! Got it installed and mostly working.

The buff icons are not displaying correctly, All I'm getting are white boxes.
![image](https://user-images.githubusercontent.com/9035933/214402114-a564ae82-35de-4774-ad89-2b8882eadc1b.png)

Any help would be apperated.

**Comment by XIBrixy** [comment]
I derped when I uploaded. Drag the bufficon folder into the assets folder. That will fix it. Or redownload the zip as i've fixed the upload also.

**Comment by wolfthefallen** [comment]
Awsome thank!
